// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpxqymilohzxcdbphueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFweHF5bWlsb2h6eGNkYnBodWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTI5MTYsImV4cCI6MjA3MjcyODkxNn0.mZwC9Jv9UOzOhesXUjEreCO9VY3d9bzz1vI1Rp6-CC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});